const STATES_CODES = [
  { "statecode": 35, "code": "AN", "name": "Andaman & Nicobar Islands" },
  { "statecode": 28, "code": "AP", "name": "Andhra Pradesh" },
  { "statecode": 12, "code": "AR", "name": "Arunachal Pradesh" },
  { "statecode": 18, "code": "AS", "name": "Assam" },
  { "statecode": 10, "code": "BR", "name": "Bihar" },
  { "statecode": 4, "code": "CG", "name": "Chandigarh" },
  { "statecode": 22, "code": "CH", "name": "Chhatisgarh" },
  { "statecode": 7, "code": "DL", "name": "Delhi" },
  { "statecode": 30, "code": "GA", "name": "Goa" },
  { "statecode": 24, "code": "GJ", "name": "Gujarat" },
  { "statecode": 6, "code": "HR", "name": "Haryana" },
  { "statecode": 2, "code": "HP", "name": "Himachal Pradesh" },
  { "statecode": 1, "code": "JK", "name": "Jammu And Kashmir " },
  { "statecode": 20, "code": "JH", "name": "Jharkhand" },
  { "statecode": 29, "code": "KA", "name": "Karnataka" },
  { "statecode": 32, "code": "KL", "name": "Kerala" },
  { "statecode": 37, "code": "LA", "name": "Ladakh" },
  { "statecode": 31, "code": "LD", "name": "Lakshadweep" },
  { "statecode": 23, "code": "MP", "name": "Madhya Pradesh" },
  { "statecode": 27, "code": "MH", "name": "Maharashtra" },
  { "statecode": 14, "code": "MN", "name": "Manipur" },
  { "statecode": 17, "code": "ML", "name": "Meghalaya" },
  { "statecode": 15, "code": "MZ", "name": "Mizoram" },
  { "statecode": 13, "code": "NL", "name": "Nagaland" },
  { "statecode": 21, "code": "OR", "name": "Odisha" },
  { "statecode": 34, "code": "PY", "name": "Puducherry" },
  { "statecode": 3, "code": "PB", "name": "Punjab" },
  { "statecode": 8, "code": "RJ", "name": "Rajasthan" },
  { "statecode": 11, "code": "SK", "name": "Sikkim" },
  { "statecode": 33, "code": "TN", "name": "Tamil Nadu" },
  { "statecode": 36, "code": "TS", "name": "Telangana" },
  { "statecode": 38, "code": "DH", "name": "The Dadra And Nagar Haveli And Daman And Diu" },
  { "statecode": 16, "code": "TR", "name": "Tripura" },
  { "statecode": 5, "code": "UK", "name": "Uttarakhand" },
  { "statecode": 9, "code": "UP", "name": "Uttar Pradesh" },
  { "statecode": 19, "code": "WB", "name": "West Bengal" }]

module.exports = {
  STATES_CODES
}
